server:
  port: 8080
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/smart_shop
    password: sardor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        diealect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true